name: pr/push checks

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'Makefile'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'Makefile'

jobs:

  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Lint
      uses: golangci/golangci-lint-action@v9

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: go test -v -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        files: coverage.out
