name: pr/push checks

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:

  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint
      uses: golangci/golangci-lint-action@v9.3.0
      with:
        version: v2.12.2

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
